package vrms;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

public class AdminDashboardPage extends JFrame {
    public AdminDashboardPage(){
        setTitle("VRMS - Admin Vehicle Catalog"); setSize(1100,680); setLocationRelativeTo(null); setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); setResizable(false);
        JPanel root=new JPanel(new BorderLayout(0,20)); root.setBackground(UIColors.BG_PAGE); root.setBorder(new EmptyBorder(24,32,24,32)); setContentPane(root); root.add(header(),BorderLayout.NORTH); root.add(cards(),BorderLayout.CENTER); root.add(bottom(),BorderLayout.SOUTH);
    }
    private JPanel header(){ JPanel h=new JPanel(new BorderLayout()); h.setOpaque(false); JPanel text=new JPanel(); text.setOpaque(false); text.setLayout(new BoxLayout(text,BoxLayout.Y_AXIS)); text.add(UIUtils.label("Vehicle Catalog",Font.BOLD,28,UIColors.TEXT_DARK)); text.add(Box.createVerticalStrut(4)); text.add(UIUtils.label("Admin view  |  Approved listings visible to customers",Font.PLAIN,13,UIColors.TEXT_MUTED)); h.add(text,BorderLayout.WEST); h.add(UIUtils.label("Admin: VRMS Admin",Font.BOLD,12,UIColors.SECONDARY),BorderLayout.EAST); return h; }
    private JScrollPane cards(){ JPanel grid=new JPanel(new GridLayout(0,3,16,16)); grid.setOpaque(false); grid.add(card("CAR","AVAILABLE","Maruti Swift","Alwin KJ","KL08AB1234","1500.00",true)); grid.add(card("BIKE","RENTED","Honda Activa","Amal Farhan","KL45CD5678","500.00",false)); grid.add(card("CAR","AVAILABLE","Toyota Innova","Arppith Andrews","KL07EF2468","2200.00",true)); JPanel holder=new JPanel(new BorderLayout()); holder.setBackground(UIColors.BG_PAGE); holder.add(grid,BorderLayout.NORTH); JScrollPane scroll=new JScrollPane(holder); scroll.setBorder(null); scroll.getViewport().setBackground(UIColors.BG_PAGE); scroll.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER); return scroll; }
    private JPanel card(String type,String status,String name,String owner,String reg,String rate,boolean deletable){ JPanel card=new JPanel(new BorderLayout(0,12)); card.setBackground(UIColors.CARD_BG); card.setPreferredSize(new Dimension(310,255)); card.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(UIColors.BORDER),new EmptyBorder(18,18,16,18))); JPanel top=new JPanel(new BorderLayout()); top.setOpaque(false); top.add(UIUtils.badge(type,UIColors.BG_LEFT,UIColors.PRIMARY),BorderLayout.WEST); top.add(UIUtils.badge(status,deletable?UIColors.SUCCESS_BG:UIColors.WARNING_BG,deletable?UIColors.SUCCESS:UIColors.WARNING),BorderLayout.EAST); card.add(top,BorderLayout.NORTH); JPanel d=new JPanel(); d.setOpaque(false); d.setLayout(new BoxLayout(d,BoxLayout.Y_AXIS)); JLabel n=UIUtils.label(name,Font.BOLD,20,UIColors.TEXT_DARK); n.setAlignmentX(Component.LEFT_ALIGNMENT); JLabel o=UIUtils.label("Listed by "+owner,Font.PLAIN,12,UIColors.TEXT_MUTED); o.setAlignmentX(Component.LEFT_ALIGNMENT); JLabel r=UIUtils.label("Registration  "+reg,Font.PLAIN,12,UIColors.TEXT_MUTED); r.setAlignmentX(Component.LEFT_ALIGNMENT); JLabel p=UIUtils.label("Rs. "+rate+" / day",Font.BOLD,17,UIColors.PRIMARY); p.setAlignmentX(Component.LEFT_ALIGNMENT); d.add(n); d.add(Box.createVerticalStrut(7)); d.add(o); d.add(Box.createVerticalStrut(4)); d.add(r); d.add(Box.createVerticalStrut(14)); d.add(p); card.add(d,BorderLayout.CENTER); JButton del=UIUtils.dangerButton(deletable?"Delete Vehicle":"Cannot Delete While Rented"); del.setEnabled(deletable); if(deletable) del.addActionListener(e->JOptionPane.showMessageDialog(this,"Delete Vehicle pressed.\nIn the final product, this removes the vehicle from the active catalog while preserving its history.","VRMS UI Preview",JOptionPane.INFORMATION_MESSAGE)); card.add(del,BorderLayout.SOUTH); return card; }
    private JPanel bottom(){ JPanel bar=new JPanel(new FlowLayout(FlowLayout.RIGHT,10,0)); bar.setOpaque(false); bar.add(UIUtils.secondaryButton("Refresh")); JButton earnings=UIUtils.secondaryButton("Earnings"); earnings.addActionListener(e->UIUtils.previewAction(this,"Earnings","opens the VRMS earnings and payment summary")); bar.add(earnings); JButton pending=UIUtils.secondaryButton("Pending Requests"); pending.addActionListener(e->UIUtils.previewAction(this,"Pending Requests","opens the pending vehicle approval list")); JPanel pc=new JPanel(new FlowLayout(FlowLayout.LEFT,5,0)); pc.setOpaque(false); pc.add(pending); pc.add(UIUtils.badge("2",UIColors.DANGER,Color.WHITE)); bar.add(pc); JButton logout=UIUtils.secondaryButton("Logout"); logout.addActionListener(e->UIUtils.previewAction(this,"Logout","ends the admin session and returns to the login screen")); bar.add(logout); return bar; }
    public static void main(String[] args){ SwingUtilities.invokeLater(()->new AdminDashboardPage().setVisible(true)); }
}
